-- Vendor shipment batches, review provenance, confirmed aliases, and OCR quota ledger.
CREATE TABLE IF NOT EXISTS shipment_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_number TEXT NOT NULL REFERENCES purchase_orders(po_number),
  vendor TEXT NOT NULL,
  reference_no TEXT NOT NULL,
  delivery_date DATE,
  tracking_no TEXT,
  tracking_provider TEXT,
  source_type TEXT NOT NULL DEFAULT 'MANUAL',
  source_file_name TEXT,
  source_file_hash TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE shipments ADD COLUMN IF NOT EXISTS shipment_batch_id INTEGER REFERENCES shipment_batches(id);
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS mapping_confidence TEXT;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS mapping_provenance TEXT;

CREATE TABLE IF NOT EXISTS vendor_item_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor TEXT NOT NULL,
  item_id TEXT NOT NULL REFERENCES master_data(item_id),
  alias TEXT NOT NULL,
  confirmed_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (vendor, item_id, alias)
);

CREATE TABLE IF NOT EXISTS shipment_ocr_usage (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_start DATE NOT NULL,
  page_count INTEGER NOT NULL CHECK (page_count > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_shipment_batches_po ON shipment_batches (po_number, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vendor_item_aliases_lookup ON vendor_item_aliases (vendor, item_id);
CREATE INDEX IF NOT EXISTS idx_shipment_ocr_usage_month ON shipment_ocr_usage (month_start);
