"use client";

import { use, useCallback, useEffect, useMemo, useState } from "react";
import { apiClient, type Lot } from "@/lib/api-client";

type Item = { itemId: string; name: string; unit: string; weeklyTarget: number; countedQty: number; requiredQty: number; revision: number };
type Order = { id: number; ownerUsername: string; jobType: string; status: "OPEN" | "CONFIRMED" | "CANCELLED"; items: Item[] };
export default function WorkOrderDetail({ params }: { params: Promise<{ id: string }> }) {
  const id = Number(use(params).id); const [order, setOrder] = useState<Order | null>(null); const [lots, setLots] = useState<Lot[]>([]); const [message, setMessage] = useState("");
  const reload = useCallback(() => Promise.all([apiClient.getCountWorkOrder(id), apiClient.getCountWorkOrderLots(id)]).then(([o, l]) => { setOrder(o); setLots(l); }), [id]);
  useEffect(() => { reload().catch((e) => setMessage(e.response?.data?.error || "โหลดใบงานไม่สำเร็จ")); }, [reload]);
  const allocations = useMemo(() => order?.items.flatMap((item) => { let remaining = Number(item.requiredQty); return lots.filter((lot: Lot & { itemId?: string }) => lot.itemId === item.itemId).map((lot) => { const qty = Math.min(remaining, Number(lot.qty)); remaining -= qty; return qty > 0 ? { itemId: item.itemId, inventoryId: lot.inventoryId, qty } : null; }).filter(Boolean); }) || [], [lots, order]);
  if (!order) return <p className="p-6">{message || "กำลังโหลด..."}</p>;
  const editable = order.status === "OPEN";
  return <section className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-2xl font-black">ใบงาน: {order.jobType || "ทุกหน่วยงาน"}</h1><p className="text-sm text-gray-500">สถานะ {order.status} · Lot ที่แสดงเป็นยอดสดจากคลังกลาง</p></div>{message && <p className="rounded-xl bg-amber-50 p-3 font-bold text-amber-800">{message}</p>}<div className="space-y-3">{order.items.map((item, index) => <article key={item.itemId} className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black">{item.name}</p><p className="text-xs text-gray-500">เป้าหมาย {item.weeklyTarget} {item.unit} · revision {item.revision}</p></div><label className="font-bold">นับได้ <input disabled={!editable} type="number" min="0" value={item.countedQty} onChange={(e) => setOrder({ ...order, items: order.items.map((x, i) => i === index ? { ...x, countedQty: Number(e.target.value), requiredQty: Math.max(Number(x.weeklyTarget) - Number(e.target.value), 0) } : x) })} className="ml-2 w-20 rounded border p-2 text-right" /></label><b className="text-blue-700">ต้องเบิก {item.requiredQty} {item.unit}</b></div></article>)}</div>{editable && <div className="flex flex-wrap gap-3"><button onClick={() => apiClient.updateCountWorkOrder(id, order.items.map((x) => ({ itemId: x.itemId, countedQty: Number(x.countedQty) }))).then(() => { setMessage("บันทึก revision แล้ว"); reload(); }).catch((e) => setMessage(e.response?.data?.error || "บันทึกไม่สำเร็จ"))} className="rounded-xl border px-5 py-3 font-bold">บันทึกยอดแก้ไข</button><button onClick={() => apiClient.confirmCountWorkOrder(id, allocations as Array<{ itemId: string; inventoryId: number; qty: number }>).then(() => { setMessage("ยืนยันเบิกเรียบร้อย"); reload(); }).catch((e) => setMessage(e.response?.data?.error || "ยืนยันไม่สำเร็จ"))} className="rounded-xl bg-ink px-5 py-3 font-bold text-white">ยืนยันเบิกตาม FEFO</button><button onClick={() => apiClient.cancelCountWorkOrder(id).then(() => { setMessage("ยกเลิกใบงานแล้ว"); reload(); })} className="rounded-xl border border-red-200 px-5 py-3 font-bold text-red-700">ยกเลิกใบงาน</button></div>}</section>;
}
